<ivy-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            version="2.0"
            xsi:noNamespaceSchemaLocation="https://ant.apache.org/ivy/schemas/ivy.xsd">

    <info organisation="de.freese"
          module="${project.artifactId}"
          revision="${project.version}"
          status="integration"
    />

    <publications>
        <artifact name="${project.artifactId}" type="jar" ext="jar" />
    </publications>

</ivy-module>